var tipuesearch = {"pages": [
     {"title": "Gold Miner", "text": "", "tags": "gold miner game gold diamonds dynamite", "url": "Games/Gold-Miner/"},
     {"title": "Jacksmith", "text": "", "tags": "jacksmith blacksmith tools donkey ore cannon", "url": "Games/Jacksmith/"},
     {"title": "Papa Louie", "text": "", "tags": "papa louie", "url": "Games/Papa-Louie/"},
     {"title": "Papa Louie 2", "text": "", "tags": "papa louie 2", "url": "Games/Papa-Louie-2/"},
     {"title": "Papa Louie 3", "text": "", "tags": "papa louie 3", "url": "Games/Papa-Louie-3/"},
     {"title": "Papa's Wingeria", "text": "", "tags": "papas papa's Wingeria", "url": "Games/Papas-Wingeria/"},
     {"title": "Papa's Cupcakeria", "text": "", "tags": "papas papa's Cupcakeria", "url": "Games/Papas-Cupcakeria/"},
     {"title": "Papa's Donuteria", "text": "", "tags": "papas papa's Donuteria", "url": "Games/Papas-Donuteria/"},
     {"title": "Papa's Pastaria", "text": "", "tags": "papas papa's Pastaria", "url": "Games/Papas-Pastaria/"},
     {"title": "Papa's Pizzeria", "text": "", "tags": "papas papa's Pizzeria", "url": "Games/Papas-Pizzeria/"},
     {"title": "Papa's Freezeria", "text": "", "tags": "papas papa's Freezeria", "url": "Games/Papas-Freezeria/"},
     {"title": "Papa's Pancakeria", "text": "", "tags": "papas papa's Pancakeria", "url": "Games/Papas-Pancakeria/"},
     {"title": "Papa's Taco Mia", "text": "", "tags": "papas papa's Taco Mia", "url": "Games/Papas-Taco-Mia/"},
     {"title": "Papa's Burgeria", "text": "", "tags": "papas pappa's Burgeria", "url": "Games/Papas-Burgeria/"},
     {"title": "Papa's Hot Doggeria", "text": "", "tags": "papas papa's Hot Doggeria", "url": "Games/Papas-Hot-Doggeria/"},
     {"title": "Cactus McCoy", "text": "", "tags": "cactus mccoy", "url": "Games/Cactus-McCoy/"},
     {"title": "Cactus McCoy 2", "text": "", "tags": "cactus mccoy 2", "url": "Games/Cactus-McCoy-2/"},
     {"title": "Steak and Jake", "text": "", "tags": "Steak and Jake", "url": "Games/Steak-and-Jake/"},
     {"title": "Steak and Jake: Midnight March", "text": "", "tags": "Steak and Jake: Midnight March", "url": "Games/Steak-and-Jake-Midnight-March/"},
     {"title": "Medieval Fury", "text": "", "tags": "fury medieval medeival exclusive", "url": "Games/Medieval-Fury/"},
     {"title": "Circle Clicker", "text": "", "tags": "circle clicker cookie", "url": "Games/Circle-Clicker/"},
     {"title": "2048", "text": "", "tags": "2048 threes", "url": "Games/2048/"},
     {"title": "The Nimpossible Game", "text": "", "tags": "hard impossible nimpossible", "url": "Games/The-Nimpossible-Game/"},
     {"title": "Sir Shield", "text": "", "tags": "sir shield shields warriors", "url": "Games/Sir-Shield/"},
     {"title": "Battle Gear: US War", "text": "", "tags": "battle gear us war", "url": "Games/Battle-Gear-US-War/"},
     {"title": "Battle Gear: Missile Attack", "text": "", "tags": "battle gear missile missiles attack attacks", "url": "Games/Battle-Gear-Missile-Attack/"},
     {"title": "Age of War", "text": "", "tags": "ages age of war wars", "url": "Games/Age-Of-War/"},
     {"title": "Age of War 2", "text": "", "tags": "ages age of war wars 2", "url": "Games/Age-Of-War-2/"},
     {"title": "Age of War 3", "text": "", "tags": "ages age of war wars 3", "url": "Games/Age-Of-War-3/"},
     {"title": "Age of War 4", "text": "", "tags": "ages age of war wars 4", "url": "Games/Age-Of-War-4/"},
     {"title": "Age of War 5", "text": "", "tags": "ages age of war wars 5", "url": "Games/Age-Of-War-5/"},
     {"title": "Age of War 6", "text": "", "tags": "ages age of war wars 6", "url": "Games/Age-Of-War-6/"},
     {"title": "Age of War 7", "text": "", "tags": "ages age of war wars 7", "url": "Games/Age-Of-War-7/"},
     {"title": "Age of War 8", "text": "", "tags": "ages age of war wars 8", "url": "Games/Age-Of-War-8/"}
]};



